services:
  times:
    container_name: times
    image: node:20
    volumes:
      - ./app:/app
    ports:
      - 5173:5173
    working_dir: /app
    command: bash -c 'npm run dev -- --host 0'
    # tty: true
